# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import two_pc_pb2 as two__pc__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in two_pc_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TwoPCServiceStub(object):
    """The Service Definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RequestVote = channel.unary_unary(
                '/twopc.TwoPCService/RequestVote',
                request_serializer=two__pc__pb2.VoteRequest.SerializeToString,
                response_deserializer=two__pc__pb2.VoteResponse.FromString,
                _registered_method=True)
        self.GlobalCommit = channel.unary_unary(
                '/twopc.TwoPCService/GlobalCommit',
                request_serializer=two__pc__pb2.DecisionRequest.SerializeToString,
                response_deserializer=two__pc__pb2.Ack.FromString,
                _registered_method=True)
        self.GlobalAbort = channel.unary_unary(
                '/twopc.TwoPCService/GlobalAbort',
                request_serializer=two__pc__pb2.DecisionRequest.SerializeToString,
                response_deserializer=two__pc__pb2.Ack.FromString,
                _registered_method=True)


class TwoPCServiceServicer(object):
    """The Service Definition
    """

    def RequestVote(self, request, context):
        """Q1: Voting Phase
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GlobalCommit(self, request, context):
        """Q2: Decision Phase (Prepared for next step)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GlobalAbort(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TwoPCServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RequestVote': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestVote,
                    request_deserializer=two__pc__pb2.VoteRequest.FromString,
                    response_serializer=two__pc__pb2.VoteResponse.SerializeToString,
            ),
            'GlobalCommit': grpc.unary_unary_rpc_method_handler(
                    servicer.GlobalCommit,
                    request_deserializer=two__pc__pb2.DecisionRequest.FromString,
                    response_serializer=two__pc__pb2.Ack.SerializeToString,
            ),
            'GlobalAbort': grpc.unary_unary_rpc_method_handler(
                    servicer.GlobalAbort,
                    request_deserializer=two__pc__pb2.DecisionRequest.FromString,
                    response_serializer=two__pc__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'twopc.TwoPCService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('twopc.TwoPCService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TwoPCService(object):
    """The Service Definition
    """

    @staticmethod
    def RequestVote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/twopc.TwoPCService/RequestVote',
            two__pc__pb2.VoteRequest.SerializeToString,
            two__pc__pb2.VoteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GlobalCommit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/twopc.TwoPCService/GlobalCommit',
            two__pc__pb2.DecisionRequest.SerializeToString,
            two__pc__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GlobalAbort(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/twopc.TwoPCService/GlobalAbort',
            two__pc__pb2.DecisionRequest.SerializeToString,
            two__pc__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
