# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: two_pc.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'two_pc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ctwo_pc.proto\x12\x05twopc\"=\n\x0bVoteRequest\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12\x16\n\x0e\x63oordinator_id\x18\x02 \x01(\t\"-\n\x0cVoteResponse\x12\x0c\n\x04vote\x18\x01 \x01(\x08\x12\x0f\n\x07node_id\x18\x02 \x01(\t\")\n\x0f\x44\x65\x63isionRequest\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\"\'\n\x03\x41\x63k\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xad\x01\n\x0cTwoPCService\x12\x36\n\x0bRequestVote\x12\x12.twopc.VoteRequest\x1a\x13.twopc.VoteResponse\x12\x32\n\x0cGlobalCommit\x12\x16.twopc.DecisionRequest\x1a\n.twopc.Ack\x12\x31\n\x0bGlobalAbort\x12\x16.twopc.DecisionRequest\x1a\n.twopc.Ackb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'two_pc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VOTEREQUEST']._serialized_start=23
  _globals['_VOTEREQUEST']._serialized_end=84
  _globals['_VOTERESPONSE']._serialized_start=86
  _globals['_VOTERESPONSE']._serialized_end=131
  _globals['_DECISIONREQUEST']._serialized_start=133
  _globals['_DECISIONREQUEST']._serialized_end=174
  _globals['_ACK']._serialized_start=176
  _globals['_ACK']._serialized_end=215
  _globals['_TWOPCSERVICE']._serialized_start=218
  _globals['_TWOPCSERVICE']._serialized_end=391
# @@protoc_insertion_point(module_scope)
